apiVersion: v1
kind: Namespace
metadata:
  name: learn-aks
---
apiVersion: v1
kind: Service
metadata:
  name: basic-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: basic-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
  labels:
    app: basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: appsvcsample/static-site
        ports:
        - containerPort: 80